[workspace]
resolver = "2"
members = ["proto", "types", "rpc"]

[workspace.dependencies]
celestia-proto = { version = "0.1.0", path = "proto" }
celestia-types = { version = "0.1.0", path = "types" }
nmt-rs = { git = "https://github.com/eigerco/nmt-rs.git", rev = "5146800" }
tendermint = "0.32"
tendermint-proto = "0.32"

[patch.crates-io]
# `cosmrs` is using terndermint from crates.io, so we patch it with ours
tendermint = { git = "https://github.com/eigerco/celestia-tendermint-rs.git", rev = "dbb4434" }
tendermint-proto = { git = "https://github.com/eigerco/celestia-tendermint-rs.git", rev = "dbb4434" }
# Uncomment to apply local changes
#tendermint = { path = "../celestia-tendermint-rs/tendermint" }
#tendermint-proto = { path = "../celestia-tendermint-rs/proto" }

[patch.'https://github.com/eigerco/nmt-rs.git']
# Uncomment to apply local changes
#nmt-rs = { path = "../nmt-rs" }
