[package]
name = "celestia-rpc"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[dependencies]
async-trait = "0.1"
celestia-types = { workspace = true }
jsonrpsee = { version = "0.20", features = ["client-core", "macros"] }
serde = { version = "1.0.188", features = ["derive"] }
thiserror = "1.0.40"
tracing = "0.1.37"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
http = "0.2.9"
jsonrpsee = { version = "0.20", features = ["http-client", "ws-client"] }

[dev-dependencies]
anyhow = "1.0.71"
dotenvy = "0.15.7"
futures = "0.3.28"
libp2p = { version = "0.52.3", features = [
  "tokio",
  "macros",
  "tcp",
  "noise",
  "yamux",
] }
rand = "0.8.5"
tokio = { version = "1.32.0", features = ["rt", "macros"] }
tracing = "0.1.37"

[features]
default = ["p2p"]
p2p = ["celestia-types/p2p"]
