[package]
name = "celestia-types"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[dependencies]
base64 = "0.21.2"
bytes = "1.4.0"
celestia-proto = { workspace = true }
nmt-rs = { workspace = true }
serde = { version = "1.0.164", features = ["derive"] }
tendermint-proto = { workspace = true }
thiserror = "1.0.40"
tendermint = { workspace = true }
sha2 = "0.10.7"

[dev-dependencies]
serde_json = "1.0.97"
