[package]
name = "celestia-types"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[dependencies]
base64 = "0.21.2"
bech32 = "0.9.1"
bytes = "1.4.0"
celestia-proto = { workspace = true }
const_format = "0.2.31"
enum_dispatch = "0.3.12"
cid = { version = "0.10.1", default-features = false, features = ["std"] }
nmt-rs = { workspace = true }
ruint = { version = "1.8.0", features = ["serde"] }
serde = { version = "1.0.164", features = ["derive"] }
sha2 = "0.10.7"
tendermint = { workspace = true }
tendermint-proto = { workspace = true }
thiserror = "1.0.40"

[dev-dependencies]
serde_json = "1.0.97"
