[package]
name = "celestia-types"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[dependencies]
base64 = "0.21.2"
bech32 = "0.9.1"
bytes = "1.4.0"
celestia-proto = { workspace = true }
const_format = "0.2.31"
enum_dispatch = "0.3.12"
cid = { version = "0.10.1", default-features = false, features = ["std"] }
libp2p-identity = { version = "0.2.3", optional = true }
multiaddr = { version = "0.18.0", optional = true }
nmt-rs = { workspace = true }
ruint = { version = "1.8.0", features = ["serde"] }
serde = { version = "1.0.164", features = ["derive"] }
serde_repr = { version = "0.1", optional = true }
sha2 = "0.10.7"
tendermint = { workspace = true }
tendermint-proto = { workspace = true }
thiserror = "1.0.40"

[dev-dependencies]
serde_json = "1.0.97"

[features]
default = ["p2p"]
p2p = ["dep:libp2p-identity", "dep:multiaddr", "dep:serde_repr"]
