[package]
name = "celestia-grpc"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
description = "A client for interacting with Celestia validator nodes gRPC"
authors = ["Eiger <hello@eiger.co>"]
homepage = "https://www.eiger.co"
repository = "https://github.com/eigerco/lumina"
readme = "README.md"
# crates.io is limited to 5 keywords and 5 categories
keywords = ["blockchain", "celestia", "lumina"]
# Must be one of <https://crates.io/category_slugs>
categories = [
  "api-bindings",
  "asynchronous",
  "encoding",
  "cryptography::cryptocurrencies",
]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
celestia-grpc-macros = { version = "0.1.0", path = "grpc-macros" }
celestia-proto = { workspace = true, features = ["tonic"] }
celestia-types.workspace = true
prost.workspace = true
tendermint-proto.workspace = true
tendermint.workspace = true

bytes = "1.8"
hex = "0.4.3"
http-body = "1"
k256 = "0.13.4"
regex = { version = "1.11", default-features = false }
serde = "1.0.215"
thiserror = "1.0.61"
tokio = { version = "1.38.0", features = ["sync"] }
tonic = { version = "0.12.3", default-features = false, features = [
  "codegen", "prost"
]}
tracing = "*"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = { version = "1.38.0", features = ["time"] }
tonic = { version = "0.12.3", default-features = false, features = [ "transport" ] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
futures = "0.3.30"
getrandom = { version = "0.2.15", features = ["js"] }
gloo-timers = { version = "0.3.0", features = ["futures"] }
send_wrapper = { version = "0.6.0", features = ["futures"] }
time = { version = "0.3.36", features = ["wasm-bindgen"] }
tonic-web-wasm-client = "0.6"

console_error_panic_hook = "0.1.7"
js-sys = "0.3.70"
serde_json = "1.0.120"
serde-wasm-bindgen = "0.6.5"
tracing-subscriber = { version = "0.3.18", features = ["time"] }
tracing-web = "0.1.3"
wasm-bindgen = "0.2.93"
wasm-bindgen-futures = "0.4.43"
web-sys = { version = "0.3.70", features = [
  "BroadcastChannel",
  "DedicatedWorkerGlobalScope",
  "Headers",
  "MessageChannel",
  "MessageEvent",
  "MessagePort",
  "Navigator",
  "Request",
  "RequestInit",
  "RequestMode",
  "Response",
  "ServiceWorker",
  "ServiceWorkerGlobalScope",
  "SharedWorker",
  "SharedWorkerGlobalScope",
  "StorageManager",
  "Window",
  "Worker",
  "WorkerGlobalScope",
  "WorkerNavigator",
  "WorkerOptions",
  "WorkerType",
] }

[dev-dependencies]
rand_core = "0.6.4"

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
dotenvy = "0.15.7"
tokio = { version = "1.38.0", features = ["rt", "macros"] }

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
# wasm-bindgen-futures = "0.4.43"
wasm-bindgen-test = "0.3.42"
