[package]
name = "lumina-node-wasm"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
description = "Browser compatibility layer for the Lumina node"
authors = ["Eiger <hello@eiger.co>"]
homepage = "https://www.eiger.co"
repository = "https://github.com/eigerco/lumina"
readme = "README.md"
# crates.io is limited to 5 keywords and 5 categories
keywords = ["blockchain", "celestia", "lumina", "node", "browser"]
# Must be one of <https://crates.io/category_slugs>
categories = [
  "asynchronous",
  "cryptography::cryptocurrencies",
  "network-programming",
  "wasm",
  "web-programming",
]

[lib]
crate-type = ["cdylib", "rlib"]

[target.'cfg(target_arch = "wasm32")'.dependencies]
celestia-types = { workspace = true }
libp2p = { workspace = true, features = ["serde"] }
lumina-node = { workspace = true }

anyhow = "1.0.71"
console_error_panic_hook = "0.1.7"
futures = "0.3"
gloo-timers = "0.3"
instant = "0.1"
js-sys = "0.3.64"
serde = { version = "1.0.164", features = ["derive"] }
serde-wasm-bindgen = "0.6.0"
serde_repr = "0.1"
thiserror = "1.0"
time = { version = "0.3", features = ["wasm-bindgen"] }
tokio =  { version = "*", features = ["sync"]}
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.18", features = ["time"] }
tracing-web = "0.1.2"
wasm-bindgen = "0.2.88"
wasm-bindgen-futures = "0.4.37"
web-sys = { version = "0.3.69", features = ["BroadcastChannel", "MessageEvent", "Worker", "WorkerOptions", "WorkerType", "SharedWorker", "MessagePort", "SharedWorkerGlobalScope"]}
enum-as-inner = "0.6"
