[package]
name = "celestia-node-wasm"
version = "0.1.0"
edition = "2021"
description = "Celestia node in WASM"
repository = "https://github.com/eigerco/celestia-node-rs"
license = "Apache-2.0"

[lib]
crate-type = ["cdylib", "rlib"]

[target.'cfg(target_arch = "wasm32")'.dependencies]
celestia-node = { workspace = true }
celestia-types = { workspace = true }
libp2p = { workspace = true }

anyhow = "1.0.71"
console_error_panic_hook = "0.1.7"
js-sys = "0.3.64"
serde = { version = "1.0.164", features = ["derive"] }
serde_repr = "0.1"
serde-wasm-bindgen = "0.6.0"
time = { version = "0.3", features = ["wasm-bindgen"] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.18", features = ["time"] }
tracing-web = "0.1.2"
wasm-bindgen = "0.2.88"
wasm-bindgen-futures = "0.4.37"
