[package]
name = "celestia-proto"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[dependencies]
prost = "0.11.9"
prost-types = "0.11.9"
tendermint-proto = { workspace = true }
serde = { version = "1.0.164", features = ["derive"] }

[build-dependencies]
anyhow = "1.0.71"
prost-build = "0.11.9"
