[package]
name = "celestia-proto"
version = "0.5.0"
edition = "2021"
license = "Apache-2.0"
description = "Rust implementation of proto structs used in celestia ecosystem"
authors = ["Eiger <hello@eiger.co>"]
homepage = "https://www.eiger.co"
repository = "https://github.com/eigerco/lumina"
readme = "README.md"
# crates.io is limited to 5 keywords and 5 categories
keywords = ["blockchain", "celestia", "lumina"]
# Must be one of <https://crates.io/category_slugs>
categories = ["encoding", "cryptography::cryptocurrencies"]

[dependencies]
celestia-tendermint-proto.workspace = true
prost.workspace = true
prost-types.workspace = true
serde = { version = "1.0.203", features = ["derive"] }
pbjson = { version = "0.7.0", optional = true }
pbjson-types = { version = "0.7.0", optional = true }
tonic = { version = "0.12.3", optional = true, default-features = false, features = [
  "codegen", "prost"
]}

[build-dependencies]
prost-build.workspace = true
prost-types.workspace = true
protox = "0.7.1"
tempfile = { version = "3.13.0", optional = true }
pbjson-build = { version = "0.7.0", optional = true }
tonic-build = { version = "0.12.3", default-features = false, optional = true, features = [ "prost" ]}

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tonic = { version = "0.12.3", optional = true, default-features = false, features = [ "transport" ] }
tonic-build = { version = "0.12.3", optional = true, default-features = false, features = ["transport"] }

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
wasm-bindgen-test = "0.3.42"

[dev-dependencies]
serde_json = "1.0.117"

[features]
tonic = [ "dep:tonic", "dep:tonic-build", "dep:pbjson", "dep:pbjson-types", "dep:pbjson-build", "dep:tempfile" ]
