[package]
name = "celestia-proto"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[dependencies]
prost = "0.12.0"
prost-types = "0.12.0"
serde = { version = "1.0.188", features = ["derive"] }
tendermint-proto = { workspace = true }

[build-dependencies]
anyhow = "1.0.75"
prost-build = "0.12.0"

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
wasm-bindgen-test = "0.3"

[dev-dependencies]
serde_json = "1.0.105"
