[package]
name = "celestia-node"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[dependencies]
celestia-proto = { workspace = true }
celestia-types = { workspace = true }
tendermint-proto = { workspace = true }

async-trait = "0.1.73"
dashmap = "5.5.3"
futures = "0.3.28"
libp2p = { version = "0.52.3", features = [
  "autonat",
  "ping",
  "gossipsub",
  "identify",
  "macros",
  "request-response",
  "kad",
] }
prost = "0.12.0"
thiserror = "1.0.48"
tokio = { version = "1.32.0", features = ["macros", "sync"] }
tracing = "0.1.37"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = { version = "1.32.0", features = ["rt-multi-thread"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { version = "0.2.10", features = ["js"] }
wasm-bindgen-futures = "0.4.37"

[dev-dependencies]
bytes = "1.4.0"
celestia-rpc = { workspace = true }
celestia-types = { workspace = true, features = ["test-utils"] }
dotenvy = "0.15.7"
libp2p = { version = "0.52.3", features = [
  "ed25519",
  "noise",
  "tcp",
  "tokio",
  "yamux",
] }
rand = "0.8.5"
serde_json = "1.0.107"
