[package]
name = "celestia-node"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[dependencies]
celestia-proto = { workspace = true }
celestia-types = { workspace = true }
tendermint-proto = { workspace = true }

async-trait = "0.1.73"
futures = "0.3.28"
libp2p = { version = "0.52.3", features = [
  "gossipsub",
  "identify",
  "macros",
  "request-response",
] }
log = "0.4.20"
prost = "0.12.0"
thiserror = "1.0.48"
tokio = { version = "1.32.0", features = ["macros", "sync"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
libp2p = { version = "0.52.3", features = ["tokio"] }
tokio = { version = "1.32.0", features = ["rt-multi-thread"] }
