name: CI

on:
  push:
  pull_request:

jobs:
  celestia-node-integration:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build the docker-compose stack
      run: docker-compose -f ci/docker-compose.yml up -d
    - name: Check running containers
      run: docker ps -a
    - name: Wait for the second block which includes the coins transfer
      run: docker-compose -f ci/docker-compose.yml logs -f | awk '$0 ~ /new head.*"height". 2/ {print;exit}'
    - name: Authorize
      run: |
        CELESTIA_NODE_AUTH_TOKEN=$(docker-compose -f ci/docker-compose.yml exec -T bridge \
          celestia bridge auth admin --p2p.network private)
        echo "CELESTIA_NODE_AUTH_TOKEN=${CELESTIA_NODE_AUTH_TOKEN}" >> "$GITHUB_ENV"
    - name: Submit a blob
      run: |
        curl -X POST \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer ${{ env.CELESTIA_NODE_AUTH_TOKEN }}" \
          -d '{
            "id": 1,
            "jsonrpc": "2.0",
            "method": "blob.Submit",
            "params": [
              [
                {
                  "namespace": "AAAAAAAAAAAAAAAAAAAAAAAAAAAADCBNOWAP3dM=",
                  "data": "8fIMqAB+kQo7+LLmHaDya8oH73hxem6lQWX1",
                  "share_version": 0,
                  "commitment": "D6YGsPWdxR8ju2OcOspnkgPG2abD30pSHxsFdiPqnVk="
                }
              ]
            ]
          }' \
          localhost:26658
    - name: logs
      run: docker-compose -f ci/docker-compose.yml logs -t
