name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Protoc
      uses: arduino/setup-protoc@v2
      with:
        version: "23.3"
        repo-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Run clippy
      run: cargo clippy --all -- -D warnings

  fmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run clippy
      run: cargo fmt -- --check

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Protoc
      uses: arduino/setup-protoc@v2
      with:
        version: "23.3"
        repo-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build the docker-compose stack
      run: |
        cat > ci/cache.json <<EOF
        {
          "target": {
            "validator": {
              "cache-from": ["type=gha,scope=validator"],
              "cache-to": ["type=gha,mode=max,scope=validator"],
              "output": ["type=docker"]
            },
            "bridge": {
              "cache-from": ["type=gha,scope=bridge"],
              "cache-to": ["type=gha,mode=max,scope=bridge"],
              "output": ["type=docker"]
            }
          }
        }
        EOF
        cd ci && docker buildx bake --file docker-compose.yml --file cache.json --load

    - name: Run the docker-compose stack
      env:
        COMPOSE_DOCKER_CLI_BUILD: 1
        DOCKER_BUILDKIT: 1 
      run: docker-compose -f ci/docker-compose.yml up --no-build -d

    - name: Wait for bridge node to start
      run: |
        docker-compose -f ci/docker-compose.yml logs -f |
          awk '/Configuration finished. Running a bridge node/ {print;exit}'

    - name: Generate auth tokens
      run: ./tools/gen_auth_tokens.sh

    - name: Run tests
      run: cargo test
