name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Protoc
      uses: arduino/setup-protoc@v2
      with:
        version: "23.3"
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Run clippy
      run: cargo clippy --all -- -D warnings

  fmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run clippy
      run: cargo fmt -- --check

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Protoc
      uses: arduino/setup-protoc@v2
      with:
        version: "23.3"
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Build the docker-compose stack
      run: docker-compose -f ci/docker-compose.yml up -d
    - name: Wait for bridge node to start
      run: |
        docker-compose -f ci/docker-compose.yml logs -f |
          awk '/Configuration finished. Running a bridge node/ {print;exit}'
    - name: Generate auth tokens
      run: ./tools/gen_auth_tokens.sh
    - name: Run tests
      run: cargo test
